import { ConfigOptions } from '../core/config';
import { CredentialOptions } from '../core/credential';
declare const BaseClient: any;
export declare class Client extends BaseClient {
    constructor({ config, credential, }: {
        config: ConfigOptions;
        credential: CredentialOptions;
    });
    cloudwatch(): any;
    cube(): any;
    ipsecvpn(): any;
    pathx(): any;
    sandbox(): any;
    uaccount(): any;
    uai_modelverse(): any;
    ubill(): any;
    ucdn(): any;
    uclickhouse(): any;
    udb(): any;
    uddb(): any;
    udisk(): any;
    udns(): any;
    udpn(): any;
    uec(): any;
    ues(): any;
    ufile(): any;
    ufs(): any;
    ugn(): any;
    uhadoop(): any;
    uhost(): any;
    uk8s(): any;
    ukafka(): any;
    ukms(): any;
    ulb(): any;
    ulight_host(): any;
    ulogservice(): any;
    umem(): any;
    umongodb(): any;
    unet(): any;
    uphone(): any;
    uphost(): any;
    usms(): any;
    uvms(): any;
    uwsc(): any;
    vpc(): any;
}
export {};
